version: '3'
services:
  nest-service:
    container_name: ${APP_CONTAINER_NAME}
    image: ${APP_IMAGE_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-net
    # my-net:
    #   ipv4_address: ${APP_CONTAINER_NETWORK_IP}
    ports:
      - ${APP_CONTAINER_PORT}:${APP_SERVER_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
  # migration:
  #   image: ${APP_IMAGE_NAME}
  #   env_file:
  #     - .env
  #   command: npm run migrate:run
  #   depends_on:
  #     - postgres
  #   networks:
  #     - my-net

  minio:
    image: minio/minio
    env_file:
      - .env
    container_name: ${MINIO_CONTAINER_NAME}
    ports:
      - ${MINIO_CONTAINER_PORT}:${MINIO_PORT}
      - '9001:9001'
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: qwe@1234
    command: server --console-address ":9001" /data
    networks:
      - my-net

  postgres:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - ${DATABASE_CONTAINER_PORT}:${DATABASE_SERVER_PORT}
    networks:
      - my-net
volumes:
  postgres-db:
  minio-storage:
networks:
  my-net:
    name: ${NET_NAME}
    external: true
