export enum ErrorMessageEnum {
  NOT_FOUND = 'Data not found',
  INTERNAL_SERVER_ERROR = 'Internal server error',
  UNAUTHORIZED = 'Unauthorized',
  FORBIDDEN = 'Access denied',
  BAD_REQUEST = 'Bad request',
  SUCCESS = 'Success',
  TOKEN_EXPIRED = 'Token expired',
  UPLOAD_FAILED = 'upload failed',
  INVALID_SIGNATURE = 'Signature is invalid or public key is changed',
  VALID_SIGNATURE = 'Signature is valid',
  KEY_NOT_FOUND = 'Key not found',
  MESSAGE_IS_CHANGED = 'Message is changed',
  PUBLIC_KEY_IS_CHANGED = 'Public key is changed',
  SIGNATURE_IS_VALID = 'Signature is valid',
}
